const ACTION_TYPES = {
  SET_BALANCE_DATA: 'SET_BALANCE_DATA',
  SET_PRODCTION_DATA: 'PRODUCTION_DATA',
  SET_SALES_DATA: 'SET_SALES_DATA',
  SET_USER_LIST: 'SET_USER_LIST',
  SET_ROLES_LIST: 'SET_ROLES_LIST',
  SET_USER_TO_UPDATE: 'SET_USER_TO_UPDATE',
  CLEAR_USER_TO_UPDATE: 'CLEAR_USER_TO_UPDATE',
  SET_CLIENTS_LIST: 'SET_CLIENTS_LIST',
  SET_CLIENT_DETAILS: 'SET_CLIENT_DETAILS',
  SET_POSTCARD_LIST: 'SET_POSTCARD_LIST',
  SET_POSTCARD_TO_UPDATE: 'SET_POSTCARD_TO_UPDATE',
  CLEAR_POSTCARD_TO_UPDATE: 'CLEAR_POSTCARD_TO_UPDATE',
  SET_POSTCARD_TYPES: 'SET_POSTCARD_TYPES',
  APP_STATE_SHOW_MODAL: 'APP_STATE_SHOW_MODAL',
  APP_STATE_HIDE_MODAL: 'APP_STATE_HIDE_MODAL',
  APP_STATE_AJAX_REQUEST_START: 'APP_STATE_AJAX_REQUEST_START',
  APP_STATE_AJAX_REQUEST_END: 'APP_STATE_AJAX_REQUEST_END',
};

export default ACTION_TYPES;